spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:sonar}
spring.datasource.username=${DB_USER:sonar}
spring.datasource.password=${DB_PASSWORD:sonar123}
spring.datasource.driver-class-name=org.postgresql.Driver