spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:exemplo}
spring.datasource.username=${POSTGRES_USER:exemplo}
spring.datasource.password=${POSTGRES_PASSWORD:exemplo}
spring.datasource.driver-class-name=org.postgresql.Driver
